language: python

addons:
  apt:
    update: true
  packages:
    libhdf5-serial-dev

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
   - python: 2.7
     os: linux
   - python: 3.4
     os: linux
   - python: 3.5
     os: linux
   - python: 3.6
     os: linux
   - python: 3.7
     dist: xenial
   - python: 3.7
     os: linux-ppc64le
     dist: bionic
   - python: 3.7
     os: linux-arm64
     dist: bionic
     
# command to install dependencies
install:
  # Upgrade distribution modules
  - "python -m pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "pip install --upgrade wheel"

  # Install build dependencies: HDF5 PATH needed for PPC64le
  - "if [ $TRAVIS_ARCH = 'ppc64le' ]; then export HDF5_DIR=/usr/lib/powerpc64le-linux-gnu/hdf5/serial; fi"
  - "env"
  - "dpkg -l"
  - "if [ $TRAVIS_ARCH = 'ppc64le' ]; then cat /proc/cpuinfo; fi"
  - "if [ $TRAVIS_ARCH = 'ppc64le' ]; then cat /etc/issue; fi"
  - "pip install -r ci/requirements_travis.txt --upgrade"

  # Print Python info
  - "python ci/info_platform.py"
  - "pip list"

  # Generate source package or wheel
  - "python setup.py build bdist_wheel"
  - "pip install ."

# command to run tests
script:
  - "python setup.py build test"
  - "python ./run_tests.py --installed"
